### ISSUE TITLE
Getting error for cmn_cost_center: org.mozilla.javascript.EvaluatorException: GlideRecord.get() - invalid table name: null 

### ISSUE THREAD

**Issue by odyvankinoby** [lvl0-io/snGet#1]
Works fine with table incident, but with table cmn_cost_center I get this error: (I xxx instance user and pw)

org.mozilla.javascript.EvaluatorException: GlideRecord.get() - invalid table name: null (sys_trigger.a723781b97c4f590a2037cf71153aff1; line 1)
EvaluatorException(JavaScript evaluation error on:
var request = new sn_ws.RESTMessageV2();request.setEndpoint('https://xxx.service-now.com/api/now/table/cmn_cost_center?sysparm_exclude_reference_link=true&sysparm_query=GOTOname%3E%3D503%5Eu_are_name%3DDI%5Eu_country%3Da08850a56ce8e1000ff5847661b85de7%5Ename%3D503');request.setHttpMethod('GET');var user = 'xxx';var password = 'xxx';request.setBasicAuth(user, password);request.setRequestHeader('Accept', 'application/json');var response = request.execute();var rec = JSON.parse(response.getBody());var results = rec['result'];for(var i = 0; i < results.length; i++){var newRec = new GlideRecord(results[i].sys_class_name);if (!newRec.get(results[i].sys_id.toString())) {newRec.sys_id = results[i].sys_id.toString();} else { gs.info(results[i].sys_id.toString());newRec.get(results[i].sys_id.toString());}for (key in results[i]) { newRec[key] = results[i][key].toString();}newRec.setWorkflow(false);newRec.autoSysFields(false);newRec.update();}
)

**Comment by odyvankinoby** [comment]
I executed the script in background script and retrieved 7 results but sys_class_name = undefined

*** Script: [object Object]
*** Script: results: 7
*** Script: results[1].sys_class_name = undefined

**Comment by odyvankinoby** [comment]
I understand this will only work with tables with sys_class_names, in dictionary we have 716 sys_class_name columns but 5760 tables without, so sys_class_name only exist for extended tables, right?
Any way to work around that issue as we only need to sync non-extended tables...

**Comment by odyvankinoby** [comment]
I updated line 56:

(...)new GlideRecord(results[i].sys_class_name)

to 

(...)new GlideRecord('" + table + "')

works fine now

**Comment by lvl0-io** [comment]
Ok, thanks!  Make sense because it doesn't have a class.  Good catch.  I'll update it and publish a new version shortly.  Glad you got it working locally.

@odyvankinoby ++

**Comment by lvl0-io** [comment]
Updated app.js based on @odyvankinoby findings.  Closing issue.
