### ISSUE TITLE
dotenv module is missing while running the node app.js file

### ISSUE THREAD

**Issue by Abakas06** [lvl0-io/snGet#3]
<img width="1015" alt="image" src="https://github.com/lvl0-io/snGet/assets/36409422/2aea96a4-cafa-4bf5-92b2-7fac04f87d69">

**Comment by lvl0-io** [comment]
Try running npm i in the snGet-main directory to install it. 

I went through the steps and this is what I get.  Note it picks up "TargetInstance" as the instance name from my .env file.

![image](https://github.com/lvl0-io/snGet/assets/106563820/baeae8e0-91b6-4840-81ce-ea67b2fbcfbc)
